server:
  port: 8085

spring:
  application:
    name: delivery-service
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      group-id: delivery-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.common.dto"
        spring.json.use.type.headers: false
        spring.json.value.default.type: "com.example.common.dto.OrderDTO"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: jdbc:postgresql://postgres:5432/delivery_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  order-service:
    url: ${gateway.url}
  delivery:
    success-rate: 0.85

gateway:
  url: ${GATEWAY_URL:http://gateway-service:8080}

api:
  auth: ${gateway.url}/api/auth
  users: ${gateway.url}/api/users
  inventory: ${gateway.url}/api/inventory
  order: ${gateway.url}/api/orders
  payment: ${gateway.url}/api/payments
  delivery: ${gateway.url}/api/delivery
  balance: ${gateway.url}/api/balances

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info

resilience4j:
  circuitbreaker:
    instances:
      orderService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3

jwt:
  secret: ${JWT_SECRET:veryverysecretkeyforjwtthatisatleast32byteslong12345}
  expiration: 3600000 # 1 hour

kafka:
  topics:
    inventory-reserved: inventory-reserved
    delivery-result: delivery-result