server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://postgres:5432/order_db
    username: postgres
    password: postgres
    hikari:
      metrics-enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: "order:com.example.order.model.Order"
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    enable:
      kafka: true
      jvm: true
      http: true
    tags:
      application: ${spring.application.name}
  tracing:
    propagation:
      type: B3,W3C
    baggage:
      correlation:
        enabled: true
        fields: userId,requestId
    sampling:
      probability: 1.0

jwt:
  secret: ${JWT_SECRET:veryverysecretkeyforjwtthatisatleast32byteslong12345}
  expiration: 3600000 # 1 hour

kafka:
  topics:
    order-created: order-created
    payment-failed: payment-failed
    delivery-result: delivery-result
