global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [
        'auth-service:8081',
        'order-service:8082',
        'payment-service:8083',
        'inventory-service:8084',
        'delivery-service:8085',
        'gateway-service:8080',
        'discovery-service:8761',
        'config-service:8888'
      ]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'