server:
  port: 8080

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://config-service:8888
  cloud:
    config:
      username: config-server
      password: ${CONFIG_SERVER_PASSWORD:configpassword}
      fail-fast: true
      retry:
        initial-interval: 2000
        max-interval: 10000
        multiplier: 2
        max-attempts: 10
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<remaining>.*), /api/auth/$\{remaining}

        - id: auth-users-service
          uri: lb://auth-service
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<remaining>.*), /api/users/$\{remaining}

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
          filters:
            - RewritePath=/api/inventory/(?<remaining>.*), /api/inventory/$\{remaining}

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - RewritePath=/api/orders/(?<remaining>.*), /api/orders/$\{remaining}

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
          filters:
            - RewritePath=/api/payments/(?<remaining>.*), /api/payments/$\{remaining}

        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/api/delivery/**
          filters:
            - RewritePath=/api/delivery/(?<remaining>.*), /api/delivery/$\{remaining}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-service:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

logging:
  level:
    root: INFO
    com.example.gateway: DEBUG
    org.springframework: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO