server:
  port: 8084

spring:
  application:
    name: inventory-service
  config:
    import: "configserver:http://config-service:8888"
  cloud:
    config:
      uri: http://config-service:8888
      fail-fast: true
      username: config-server
      password: ${CONFIG_SERVER_PASSWORD:configpassword}

logging:
  level:
    root: INFO
    com.example.inventory: INFO
    org.springframework: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
