name: e2e

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
    e2e-tests:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Setup java
            uses: actions/setup-java@v4
            with:
              distribution: 'temurin'
              java-version: '17'
          - name: Setup gradle
            uses: gradle/actions/setup-gradle@v4
            with:
              gradle-version: '7.6.1'
