name: Build and Test Auth Service

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [
          'auth-service'
        ]
    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Verify Docker
        run: |
          docker ps
          docker version

      - name: Build ${{ matrix.module }}
        run: gradle :${{ matrix.module }}:build -x test --info

      - name: Run tests for ${{ matrix.module }}
        run: gradle :${{ matrix.module }}:test --info

      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-report-${{ matrix.module }}
          path: ${{ github.workspace }}/${{ matrix.module }}/build/reports/tests/test