name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged

    strategy:
      matrix:
        module: [
          'discovery-service',
          'config-service',
          'gateway-service',
          'auth-service',
          'order-service',
          'payment-service',
          'delivery-service',
          'inventory-service',
          'common-dto'
        ]
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          check-latest: true

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '7.6.1'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Enable Testcontainers
        run: |
          echo "TESTCONTAINERS_RYUK_DISABLED=true" >> $GITHUB_ENV
          echo "DOCKER_HOST=tcp://docker:2375" >> $GITHUB_ENV
          echo "GRADLE_OPTS=-Dorg.gradle.daemon=false" >> $GITHUB_ENV

      - name: Verify Docker
        run: docker info

      - name: Build ${{ matrix.module }}
        run: |
          if [[ "${{ matrix.module }}" != "common-dto" ]]; then
            gradle :${{ matrix.module }}:bootJar
          else
            gradle :${{ matrix.module }}:build
          fi

      - name: Run tests for ${{ matrix.module }}
        timeout-minutes: 10
        run: gradle :${{ matrix.module }}:test --info
        continue-on-error: true

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report-${{ matrix.module }}
          path: ${{ github.workspace }}/${{ matrix.module }}/build/reports/tests/test