name: Build and Test Auth Service

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container
          endpoint: tcp://docker:2375
          install: true

      - name: Configure Testcontainers
        run: |
          echo "DOCKER_HOST=tcp://docker:2375" >> $GITHUB_ENV
          echo "TESTCONTAINERS_RYUK_DISABLED=true" >> $GITHUB_ENV
          echo "TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock" >> $GITHUB_ENV

      - name: Verify Docker
        run: |
          docker ps
          docker version

      - name: Build and Test
        run: |
          gradle :auth-service:build --info
          gradle :auth-service:test --info