name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '7.6.1'

    - name: Build project
      run: gradle build -x bootJar

    - name: Build service JARs
      run: |
        gradle :discovery-service:bootJar
        gradle :config-service:bootJar
        gradle :gateway-service:bootJar
        gradle :auth-service:bootJar
        gradle :order-service:bootJar
        gradle :payment-service:bootJar
        gradle :delivery-service:bootJar
        gradle :inventory-service:bootJar

    - name: Run tests
      run: |
        gradle :discovery-service:test
        gradle :config-service:test
        gradle :gateway-service:test
        gradle :auth-service:test
        gradle :order-service:test
        gradle :payment-service:test
        gradle :delivery-service:test
        gradle :inventory-service:test
        gradle :common-dto:test
        gradle :integration-test:test