name: Build and Test Auth Service

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '7.6.1'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Verify Docker
        run: |
          docker ps
          docker version

      - name: Build and Test All Modules
        run: |
          # Собираем все модули кроме корневого
          ./gradlew build -x bootJar -x :integration-test:build
          ./gradlew test -x :integration-test:test