name: Build and Test Auth Service

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.set-modules.outputs.modules }}
    steps:
      - uses: actions/checkout@v4
      - id: set-modules
        run: |
          MODULES=$(grep "include '" settings.gradle | sed -e "s/include '\(.*\)'/\1/g" | grep -v "integration-test" | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "modules=$MODULES" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ${{ fromJson(needs.prepare.outputs.modules) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '7.6.1'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Module ${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}:build

      - name: Test Module ${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}:test

      - name: Check Code Coverage
        run: ./gradlew :${{ matrix.module }}:jacocoTestCoverageVerification

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.module }}
          path: ${{ matrix.module }}/build/reports/jacoco/test/html/

  integration-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '7.6.1'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start Services
        run: |
          docker-compose up -d
          sleep 60

      - name: Run Integration Tests
        run: ./gradlew :integration-test:test

      - name: Check Integration Test Coverage
        run: ./gradlew :integration-test:jacocoTestCoverageVerification

      - name: Upload Integration Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: integration-coverage-report
          path: integration-test/build/reports/jacoco/test/html/

      - name: Stop Services
        if: always()
        run: docker-compose down

  summary:
    needs: integration-tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check build status
        if: needs.build.result == 'failure'
        run: exit 1
